"""Write docs/mcp-tools.json from the running MCP server's own tool list.

    uv run python scripts/export_tool_spec.py

The file is a readable copy of what an MCP client receives from `tools/list`, plus
the limits the tools enforce. tests/test_tool_spec.py regenerates it in memory and
fails if the committed file is out of date, so the two cannot drift apart.
"""

import asyncio
import json
from contextlib import asynccontextmanager
from pathlib import Path

from mcp import Client

from freshdesk_connector import normalize, service
from freshdesk_connector.server import INSTRUCTIONS, create_server

SPEC_PATH = Path(__file__).resolve().parent.parent / "docs" / "mcp-tools.json"


@asynccontextmanager
async def _no_service():
    # Listing tools never touches Freshdesk, so no service (and no credentials) is needed.
    yield None


async def build_spec() -> dict:
    async with Client(create_server(_no_service)) as client:
        tools = (await client.list_tools()).tools
    return {
        "$comment": "Generated by scripts/export_tool_spec.py from the MCP server. Do not edit by hand.",
        "server": {
            "name": "freshdesk-tickets",
            "instructions": INSTRUCTIONS,
            "transports": ["stdio (default)", "streamable-http (--transport http, binds 127.0.0.1)"],
            "read_only": True,
            "write_tools": [],
        },
        "limits": {
            "list_tickets.max_page": service.LIST_MAX_PAGE,
            "list_tickets.max_page_size": service.LIST_MAX_PAGE_SIZE,
            "search_tickets.page_size": service.SEARCH_PAGE_SIZE,
            "search_tickets.max_page": service.SEARCH_MAX_PAGE,
            "search_tickets.max_reachable_results": service.SEARCH_MAX_REACHABLE,
            "scan.max_tickets (keyword and oldest_first)": service.SCAN_MAX_TICKETS,
            "scan.time_budget_seconds": service.SCAN_TIME_BUDGET_SECONDS,
            "keyword.length": [service.KEYWORD_MIN_CHARS, service.KEYWORD_MAX_CHARS],
            "keyword.default_lookback_days": service.KEYWORD_DEFAULT_LOOKBACK_DAYS,
            "get_ticket.description_max_chars": normalize.DESCRIPTION_MAX_CHARS,
        },
        "tools": [tool.model_dump(by_alias=True, exclude_none=True, mode="json") for tool in tools],
    }


def render(spec: dict) -> str:
    return json.dumps(spec, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    SPEC_PATH.write_text(render(asyncio.run(build_spec())), encoding="utf-8", newline="\n")
    print(f"wrote {SPEC_PATH.relative_to(Path.cwd()) if SPEC_PATH.is_relative_to(Path.cwd()) else SPEC_PATH}")


if __name__ == "__main__":
    main()
